# Should we listen on CraftEngineReloadEvent [/ce reload all] and automatically refresh the menu?
# If false, use [/cea reload] to refresh manually.
automatic-reload: true

# Should we delay the automatic menu refresh? (Ignored if automatic-reload is FALSE)
# Waits 60 ticks (3 seconds) before refreshing the menu.
refresh-delay: 60

# When reading into CraftEngine files, which directories should we ignore?
excluded-directories:
  - "resourcepack"
  - "legacy_armor"
  - "remove_shulker_head"

# What GUI should we use? By default, we use CraftEngine's.
menu-title: "§f<shift:-11><image:internal:item_browser>"